PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX t: <http://www.onto.net/core/>
PREFIX a: <http://www.onto.net/abox/heads-and-tails/>

SELECT ?transition_mode ?variable_name ?value
FROM <http://localhost:3030/ontonet/data/tbox>
FROM <http://localhost:3030/ontonet/data/abox>
WHERE {
  ?transition_mode rdf:type t:TransitionMode;
                   t:has_binding ?binding.
  ?binding t:has_variable ?variable;
           t:has_data ?data.
  ?variable t:has_value ?variable_name.
  ?data t:has_value ?value.
  FILTER NOT EXISTS {
    ?multiset_tm rdf:type t:Multiset;
                 t:has_basisSet ?basis_set_tm.
    ?basis_set_tm t:has_data ?transition_mode.
  }
}
