PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX t: <http://www.onto.net/core/>
PREFIX a: <http://www.onto.net/abox/heads-and-tails/>

# Getting the combinations and disaggregating them back row by row
SELECT ?transition_mode ?binding
WHERE {
  OPTIONAL {
    BIND(IRI(CONCAT(STR(a:), "tm_", STRUUID())) as ?transition_mode)
  }
  VALUES ?a { "one" <NULL> }
  VALUES ?b { "two" <NULL> }
  VALUES ?c { "three" <NULL> }
  FILTER (?a != <NULL> || ?b != <NULL> || ?c != <NULL>)
  
  {
    VALUES ?a { "one" }
    BIND ("a value" as ?binding)
  } UNION {
    VALUES ?b { "two" }
    BIND ("b value" as ?binding)
  } UNION {
    VALUES ?c { "three" }
    BIND ("c value" as ?binding)
  }
}
ORDER BY ?transition_mode
