PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX t: <http://www.onto.net/core/>
PREFIX a: <http://www.onto.net/abox/heads-and-tails/>

WITH <http://localhost:3030/ontonet/data/abox>
DELETE {
  
}
INSERT {
  ?transition_modes_ms rdf:type t:Multiset;
                       t:has_transition ?transition;
                       t:has_basisSet ?transition_mode_bs.
  ?transition_mode_bs rdf:type t:BasisSet;
                      t:has_multiplicity 1;
					  t:has_data ?transition_mode.
  ?transition_mode rdf:type t:TransitionMode;
                   t:has_binding ?binding.
}
WHERE {
  # selection
  ?transition rdf:type t:Transition.
  BIND(IRI(CONCAT(STR(a:), "tm_", STRUUID())) as ?transition_mode)
  {
    SELECT *
    WHERE {
      ?arc rdf:type t:Arc;
	       t:has_targetNode ?transition;
           t:has_multisetOfTerms ?annotation_ms.
      ?annotation_ms t:has_basisSet ?annotation_bs.
      ?annotation_bs t:has_multiplicity ?annotation_mul.
      ?binding rdf:type t:Binding;
               t:has_data ?data;
		       t:has_variable ?variable;
		       t:has_token ?token_bs;
		       t:has_annotationChunk ?annotation_bs.
      # Bindings must be leaf (free)
      FILTER NOT EXISTS {
        ?transition_mode rdf:type t:TransitionMode;
	                     t:has_binding ?binding.
      }
      ?data t:has_value ?value.
      ?variable t:has_value ?variable_name.
      ?token_bs t:has_data ?token_data;
                t:has_multiplicity ?token_mul.
      ?token_data t:has_value ?token_value.
    }
  }
  
  # filtration
}