PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX t: <http://www.onto.net/core/>
PREFIX a: <http://www.onto.net/abox/heads-and-tails/>

WITH <http://localhost:3030/ontonet/data/abox>
DELETE {
  
}
INSERT {
  ?transition_modes_ms rdf:type t:Multiset;
                       t:has_transition ?transition;
                       t:has_basisSet ?transition_mode_bs.
  ?transition_mode_bs rdf:type t:BasisSet;
                      t:has_multiplicity 1;
					  t:has_data ?transition_mode.
  ?transition_mode rdf:type t:TransitionMode;
                   t:has_binding ?binding.
}
WHERE {
  # selection
  BIND(IRI(CONCAT(STR(a:), "tm_", STRUUID())) as ?transition_mode)
  VALUES ?a { "one" undef }
  VALUES ?b { "two" undef }
  VALUES ?c { "three" undef }
  FILTER (BOUND(?a) || BOUND(?b) || BOUND(?c))
  
  # filtration
}