PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX t: <http://www.onto.net/core/>
PREFIX a: <http://www.onto.net/abox/heads-and-tails/>

WITH <http://localhost:3030/ontonet/data/abox>
INSERT {
  ?binding rdf:type t:Binding;
		   t:has_variable ?variable;
		   t:has_data ?data;
		   t:has_token ?token_bs;
		   t:has_annotationChunk ?annotation_chunk_bs.
  ?data rdf:type t:Data;
        t:has_value ?value.
}
WHERE {
  BIND(IRI(CONCAT(STR(a:), "binding_", STRUUID())) as ?binding)
  BIND(IRI(CONCAT(STR(a:), "data_", STRUUID())) as ?data)
  {
    ?variable rdf:type t:Variable;
	          t:has_value "<var_name>".
	BIND("<json_var_value>" as ?value)
	BIND(<token_bs_uri> as ?token_bs)
	BIND(<annotation_chunk_bs_uri> as ?annotation_chunk_bs)
  }
  UNION
  {}
}